spring:
  profiles:
    active: dev 
---
server:
  port: 8101
spring: 
  profiles: dev 
  application:
    name: '{cipher}514b8eb69f0757b77fc4984f0a91451e129b120877e66176dd7c13a304cab84e110115b0ccc6ca161a655c72b952f3c2'   
eureka:
  client: 
    service-url: 
      defaultZone: http://eadmin:111111@eureka-node104-7001.com:7001/eureka,http://eadmin:111111@eureka-node105-7001.com:7001/eureka,http://eadmin:111111@eureka-node106-7001.com:7001/eureka 
---
server:
  port: 8102
spring: 
  profiles: beta 
  application:
    name: microcloud-config-client  
eureka:
  client: 
    service-url: 
      defaultZone: http://eadmin:111111@eureka-node104-7001.com:7001/eureka,http://eadmin:111111@eureka-node105-7001.com:7001/eureka,http://eadmin:111111@eureka-node106-7001.com:7001/eureka 